name: deploy

on:
  push:
    branches:
      - main

jobs:
  push-to-gh-page:
    if: "contains(github.event.head_commit.message, 'ci:')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Build
        run: |
          yarn install --frozen-lockfile
          yarn run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./.vitepress/dist
